ShopBundle\ReadModel\Product:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: int
        name:
            expose: true
            type: string
        price:
            expose: true
            type: Money\Money
        taxName:
            expose: true
            type: string
        taxRate:
            expose: true
            type: float
        categoryName:
            expose: true
            type: string