services:
  shop.default_controller:
    class: ShopBundle\Controller\DefaultController
    arguments:
        - '@tactician.commandbus.default'

  shop.category_repository:
    class: ShopBundle\Repository\Category\CategoryRepository
    factory: ['@doctrine', getRepository]
    arguments:
      - ShopBundle:Category


  shop.category_create_handler:
      class: ShopBundle\CommandHandler\Category\CreateCategory
      arguments:
          - '@shop.category_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Category\CategoryCommand, bus: queued }
