services:
  shop.default_controller:
    class: ShopBundle\Controller\DefaultController
    arguments:
        - '@tactician.commandbus.default'

  shop.category_repository:
    class: ShopBundle\Repository\Category\CategoryRepository
    factory: ['@doctrine', getRepository]
    arguments:
      - ShopBundle:Category

  shop.category_create_handler:
      class: ShopBundle\CommandHandler\Category\CreateCategory
      arguments:
          - '@shop.category_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Category\CategoryCommand, bus: queued }

  shop.tax_repository:
    class: ShopBundle\Repository\Tax\TaxRepository
    factory: ['@doctrine', getRepository]
    arguments:
      - ShopBundle:Tax

  shop.tax_create_handler:
      class: ShopBundle\CommandHandler\Tax\CreateTax
      arguments:
          - '@shop.tax_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Tax\CreateTaxCommand, bus: queued }

  shop.money_factory:
      class: ShopBundle\Factory\MoneyFactory
      arguments:
          - "PLN"

  shop.product_read_model_factory:
      class: ShopBundle\Factory\ProductReadModelFactory
      arguments:
        - '@shop.money_factory'

  shop.product_query:
      class: ShopBundle\Query\Product
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@shop.product_read_model_factory'