services:
  shop.category_repository:
    class: ShopBundle\Repository\Category\CategoryRepository
    factory: ['@doctrine', getRepository]
    arguments:
      - ShopBundle:Category

  shop.category_create_handler:
      class: ShopBundle\CommandHandler\Category\CreateCategory
      arguments:
          - '@shop.category_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Category\CategoryCommand, bus: queued }

  shop.tax_repository:
    class: ShopBundle\Repository\Tax\TaxRepository
    factory: ['@doctrine', getRepository]
    arguments:
      - ShopBundle:Tax

  shop.product_repository:
      class: ShopBundle\Repository\Product\ProductRepository
      factory: ['@doctrine', getRepository]
      arguments:
        - ShopBundle:Product

  shop.product_create_handler:
      class: ShopBundle\CommandHandler\Product\CreateProduct
      arguments:
          - '@shop.product_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Product\ProductCommand, bus: queued }

  shop.tax_create_handler:
      class: ShopBundle\CommandHandler\Tax\CreateTax
      arguments:
          - '@shop.tax_repository'
      tags:
          - { name: tactician.handler, command: ShopBundle\Command\Tax\CreateTaxCommand, bus: queued }

  shop.money_factory:
      class: ShopBundle\Factory\MoneyFactory
      arguments:
          - "%shop.currency_code%"

  shop.product_read_model_factory:
      class: ShopBundle\Factory\ProductReadModelFactory
      arguments:
        - '@shop.money_factory'

  shop.product_query:
      class: ShopBundle\Query\Product
      arguments:
        - '@doctrine.orm.default_entity_manager'
        - '@shop.product_read_model_factory'

  shop.cart_service:
      class: ShopBundle\Service\Cart\SessionCartService
      arguments:
        - '@session'
        - '%shop.cart_session_key%'
        - '@shop.cart_serializer'

  shop.cart_serializer:
      class: ShopBundle\Service\Cart\JMSCartSerializer
      arguments:
        - '@jms_serializer'