ui_html_homepage:
    path:     /
    defaults: { _controller: UIHtmlBundle:Default:index }

ui_html_cart:
    path:     /cart
    defaults: { _controller: UIHtmlBundle:Default:cart }

ui_html_add_to_cart:
    path:     /addToCart/{productId}
    defaults: { _controller: UIHtmlBundle:Default:addToCart }
    requirements:
      productId: '\d+'

ui_html_cart_update:
    path:     /cartUpdate
    defaults: { _controller: UIHtmlBundle:Default:cartUpdate }
    methods: [POST]
